clone from empty branch
AlexChirkin/test-graphql pull request #1
Opened 2020-05-31 14:44 UTC by AlexChirkin

2020-06-01 19:20 UTC, shtbik requested changes
4/5, давай немного пооптимизируем?

2020-06-01 19:20 UTC, shtbik commented on .babelrc
> +      ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal"}],
```suggestion
      ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
```

2020-06-01 19:20 UTC, shtbik commented on .eslintrc.js
> +        "eslint:recommended",
Одинаковое значение в строке https://github.com/AlexChirkin/test-graphql/pull/1/files#diff-e4403a877d80de653400d88d85e4801aR7

2020-06-01 19:20 UTC, shtbik commented on package.json
> +    "moment": "^2.26.0",
Совет, можно заменить на dayjs - https://medium.com/datadriveninvestor/https-medium-com-sabesan96-why-you-should-choose-day-js-instead-of-moment-js-9cf7bb274bbd

2020-06-01 19:20 UTC, shtbik commented on package.json
> +    "eslint-plugin-import": "^2.20.2",
В devDependencies

2020-06-01 19:20 UTC, shtbik commented on src/components/Header/Header.js
> +export const Header = () => <div className={headerStyles.header}>Github API (GraphQL)</div>
Почему бы не сделать `export default`? https://github.com/AlexChirkin/test-graphql/pull/1/files#diff-14b1e33d5bf5649597cdc0e4f684daddR2

2020-06-01 19:20 UTC, shtbik commented on src/App.js
> +  <div className="App">
className не используется, можно обернуть в `<></>`

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import React, {useCallback} from "react";
```suggestion
import React, { useCallback } from "react";
```

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import { GET_LICENSE } from "../../../gql/query/fetchData";
По поводу порядка, видимо линтеру нужно помочь
https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +const FilterLicense = (props) => {
```suggestion
const FilterLicense = ({ setLicense, setCursor, defaultCursorParam }) => {
```

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import filterStyles from "./FilterLicense.module.css";
Почему решил использовать css, а не [scss](https://blog.bitsrc.io/how-to-use-sass-and-css-modules-with-create-react-app-83fa8b805e5e)?

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +  const { data } = useQuery(GET_LICENSE);
Лайк за получение списка лицензий с сервера

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import Select from "react-select";
Шрифт разный, т.к. в либе используют не нативный элемент

<img width="129" alt="Снимок экрана 2020-06-01 в 21 49 48" src="https://user-images.githubusercontent.com/12717213/83443371-49c2d400-a452-11ea-8694-9beba860c530.png">

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +        options={data?.licenses?.map((v) => ({value: v?.key,label: v?.name,}))}
Точно нужно столько проверок в цикле? Может просто не выводить компонент, если `data.licenses` не пришла?

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Pagination/Pagination.js
> +    return () => {};
Думаю это необязательно

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Pagination/Pagination.js
> +        before: action === "prev" ? beforeCursor : null,
Давай вынесем проверку в переменную, чтобы не дублировать `action === "prev"`?

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Pagination/Pagination.js
> +        after: action === "prev" ? null : afterCursor,
```suggestion
        after: action === "next" ? afterCursor : null,
```

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Search/Search.js
> +          onChange={(e) => setInputVal(e.target?.value)}
Просто интересный холиварчик [1](https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578), [2](https://flexport.engineering/ending-the-debate-on-inline-functions-in-react-8c03fabd144)

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Search/Search.module.css
> +.form .formBtn:disabled {
К слову, https://github.com/AlexChirkin/test-graphql/pull/1/files#diff-a61d983be5ca1235850d4509ff41ccdeR6

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Table/Table.js
> +          {data.map((v) => (
Больше деструктуризации многоликому богу

2020-06-01 19:20 UTC, shtbik commented on src/components/Repositories/Table/Table.js
> +              <td>{v.node.primaryLanguage?.name || "\u2014"}</td>
"\u2014" можно вынести в переменную

2020-06-01 20:11 UTC, AlexChirkin commented on .eslintrc.js
> +        "eslint:recommended",
fixed

2020-06-01 20:11 UTC, AlexChirkin commented on package.json
> +    "moment": "^2.26.0",
думаю что тут не принципиально

2020-06-01 20:11 UTC, AlexChirkin commented on package.json
> +    "eslint-plugin-import": "^2.20.2",
fixed

2020-06-01 20:13 UTC, AlexChirkin commented on src/components/Header/Header.js
> +export const Header = () => <div className={headerStyles.header}>Github API (GraphQL)</div>
fixed

2020-06-01 20:13 UTC, AlexChirkin commented on src/App.js
> +  <div className="App">
fixed

2020-06-01 20:17 UTC, AlexChirkin commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import { GET_LICENSE } from "../../../gql/query/fetchData";
Добавил конфиг отсюда, линтеру это не помогло. Нужно кастомно настраивать основываясь на мнение о прекрасном которое формирует команда проекта

2020-06-01 20:25 UTC, AlexChirkin commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +const FilterLicense = (props) => {
fixed

2020-06-01 20:27 UTC, AlexChirkin commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import filterStyles from "./FilterLicense.module.css";
В тестовом верстать ничего сложного не нужно было, на каждый компонент по паре классов, читаемость не пострадает от этого, счел излишним scss

2020-06-01 20:37 UTC, AlexChirkin commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import Select from "react-select";
fixed

2020-06-01 20:40 UTC, AlexChirkin commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +        options={data?.licenses?.map((v) => ({value: v?.key,label: v?.name,}))}
С? тех? пор? как? появился? optional? chaining?, мне? очень? полюбилось? ставить? вопросики?, возможно? не всегда? к? месту?, оставил как есть =)

2020-06-01 20:43 UTC, AlexChirkin commented on src/components/Repositories/Pagination/Pagination.js
> +    return () => {};
fix

2020-06-01 20:44 UTC, AlexChirkin commented on src/components/Repositories/Pagination/Pagination.js
> +        before: action === "prev" ? beforeCursor : null,
fix

2020-06-01 20:45 UTC, AlexChirkin commented on src/components/Repositories/Pagination/Pagination.js
> +        after: action === "prev" ? null : afterCursor,
action === "prev" вынес в переменную, не вижу смысла плодить еще одну для того чтобы поменять очередность

2020-06-01 20:48 UTC, AlexChirkin commented on src/components/Repositories/Search/Search.js
> +          onChange={(e) => setInputVal(e.target?.value)}
Можно заменить на useCallback, оставил как есть

2020-06-01 20:48 UTC, AlexChirkin commented on src/components/Repositories/Search/Search.module.css
> +.form .formBtn:disabled {
ответил там

2020-06-01 20:54 UTC, AlexChirkin commented on src/components/Repositories/Table/Table.js
> +          {data.map((v) => (
Вынес const {node} = v, если ты про это имел ввиду. На самом деле не особо вижу смысла разбивать этот объект на меньшие части, обсуждаемо

2020-06-01 20:56 UTC, AlexChirkin commented on src/components/Repositories/Table/Table.js
> +              <td>{v.node.primaryLanguage?.name || "\u2014"}</td>
fix

2020-06-02 07:56 UTC, shtbik commented on src/components/Repositories/FilterLicense/FilterLicense.js
> +import filterStyles from "./FilterLicense.module.css";
ок

2020-06-02 07:58 UTC, shtbik commented on src/components/Repositories/Pagination/Pagination.js
> +        after: action === "prev" ? null : afterCursor,
ок

2020-06-02 08:03 UTC, shtbik commented on src/components/Repositories/Table/Table.js
> +          {data.map((v) => (
Я имел ввиду так `{data.map(( { node: { ... } } ) => (`, но уже вижу, что у тебя дальше не факт, что node придет

2020-06-02 08:04 UTC, shtbik approved these changes

2022-03-22 11:49 UTC, merged